### ISSUE TITLE
what is self.dataset_index[key]?

### ISSUE THREAD

**Issue by xorangecheng** [tarun005/USSS_ICCV19#4]
Hi, thanks for sharing your work.
I would like to know what is the self.d_id and self._dataset_index in the EntropyLoss?

Thanks in advance.

Best,

**Comment by tarun005** [comment]
self.d_id was the dataset id {0,1} and self._dataset_index has the ids in the current batch which correspond to the particular datasets.

However, they are not relevant to the code, since they are used only when updating the prototype embedding. In our work, we did not explore the possibility of updating the embedding during training.

Sorry for the confusion. Modified the code now.
